namespace: billing-prod
replicaCount: 2

image:
  repository: ACCOUNT_ID.dkr.ecr.eu-west-3.amazonaws.com/billing/frontend
  tag: "latest"
  pullPolicy: Always

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"
