name: boutique-service
port: 8088
image:
  repository: 005988778995.dkr.ecr.us-east-1.amazonaws.com/billing/boutique-service
  tag: "10"
dbConfigMapKey: BOUTIQUE_DATASOURCE_URL
extraEnv:
  - name: KAFKA_BOOTSTRAP_SERVERS
    valueFrom: KAFKA_BOOTSTRAP_SERVERS
  - name: CUSTOMER_SERVICE_URL
    valueFrom: CUSTOMER_SERVICE_URL
  - name: CATALOG_SERVICE_URL
    valueFrom: CATALOG_SERVICE_URL
  - name: SUBSCRIPTION_SERVICE_URL
    valueFrom: SUBSCRIPTION_SERVICE_URL
