---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: billing-secret
  namespace: billing-prod
spec:
  encryptedData:
    DB_PASSWORD: AgBnaPOfolq+Mq78fauiiF8NkVo2J085juR4iL6E4gzK92uZWVqK2t55Y1Hy29Kf5Y6Kdr++8XWpY4nFKW8oVVkuudohw+jSMA6YvUM8sRm+67OvqPuOAAvxy2Tgw7SFDUKZFdNWSkULNtf/4STqqupXxnPqHdrLsHqYO363FiBwIhLHFbsHiTOOx0nBjgo3zqVTQzckp6FbzYwRJRuhtG9rQPoFGRRAP8tlyPuC3CvOm+gc1XkwjTbDdDflv4C6R/w5DXLDYnh/NBA/fJuPjl2Yd4gzffTTdXThEh2e7LEHPLEobKRju/U7/CsMo0C6GD3EAQqxpAOV6DgC0v8sFEcxKnjfnhv7XuWCxjRDf4mXx2YGEoDhkADiKYHU010tDd/SaS0vrgCz2XMB4oWhO7IKeHHH+yl7vwYX4hhNFGObFjAeTXBXM0efUHmtyZtcX/44jJbFlql82/w4Xy1o7xEUei4zN9z0IUsanWdi0GQSu/R5BhKgJr7SICeRzmxzS4z31OvdVT+r/yx+h86KAexVOUs2+f4rqfW9t7FlrJTx/wxNU5+UNsCqe3Dz7f+btFkfsUJORXV/jpDt+tvs2/5UKKFxJtHwTjyn1NVOFqGWq3fCNkTo1lGc2lc4TOdpvtARJ7BWBxrIAREwhyo8Lt9qPqueM21/vNwXMCrRY3vVFk0gI9wpGOFAOhqIxd3eptbFKm50
    JWT_SECRET: AgBhrJzGzafiliyou91Z17KgoE6XoEJcmJ7+MOTCEl+zfKgJWVQ07qmvCpchSBsGd48yksyHIh9Jx3kSot0QcMf0guVTJzUf3/crZOOqf7zNUFeCw1NZUWaHCHKbVF1zjiuOE44oMAzhBLwRKCdGFX8XKA/qcGMOEjo/NKEYdpBxhIa/V+9D4VZ9iOEm22BVw0Mk8w5mGJ/y/688RVr5LuthmoR7r+40+z1352gBzA2mrgDf50YRhGht+X34rPh3NLwUYRD4f4mAScEqLypikAluSCSzbn6NTAyMzpT2ZI0KxrjxCzxVhiIbFTkfk7jrB0n8YI1sVK+l+C0DHYVZuS5lZazRrWCSC0XQFaKpmomn2tk9NlMINhhZS5Gk6HFcAISxSRhkWE9L42hq4WdS39U3SPH3sBZWqXnIT556AR2ax3SN33GnO7eDy/i1+CB3BXEhVg/Vy+A13H2LIiVG2j02BFmQhCjRhHUuCWFBM9PomXz7enNqM5wXGipV1RPLUjoaYkgBRUxz86OzB1608SEr5PjWgqF+w7fcklnlfJHgQGiP7ub9Lk0f9HkS2iSaXoeC/QBEeU4zUYujEfv23fZudnWiNzaqqQHE+7hVBSH2KxKdSFXI2Gtn7UMqFEwFXzUM0OHEJDzR4SxE5h82mWjJLYwpENR0bTFqrBw59CGuVav+SZxWNvlTW9I9I8V4Gs8Uv9n7HUIJTtRWIhQBWqtJ36M36ahrvS3pokGHoohT/EvkSA==
  template:
    metadata:
      creationTimestamp: null
      name: billing-secret
      namespace: billing-prod
    type: Opaque
