---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: billing-secret
  namespace: billing-prod
spec:
  encryptedData:
    DB_PASSWORD: AgAyuqnFhPlYjwOBLzzEP2NSRRAm6bmKmgwOajwrLVvz4dQnaC9y/nuuWtHr4Zcnj2z8ngz2etc9rl2wCxWyQoxl7+5GMT5kLWv88wqaB1raXxcQPBYg4NyONyp2i+NUhxi920T13ECBA3GJd92G+AmuY9M5cxGhv+w6Oz5EPPWlV/tGma8a/rx7i0altxVeg7gXEPjRLn3C08873AA0E5KnedFfj57Me5/Jxoxktfe5rds183U5U6QHgGorPdzF1RbD6qDY+k6GmGEeRwF1xfQ2doROi+8h97KngRagZtWAldn0f4rWWBhJas19ChcBlu+7VbA/vP8BsNEV1Et7mkTo4HV2Fh/jRrGh6tmpwdCILtyZiaarpdCsS0nwY33C8Ae6bJ59w9cit09c57HLzrUV087CgPw+ACPyGxjP474VkspxRMt8aMT50TE8HGZCXqUIcjH30EUtVPP1mgim2z9SDictj+sVte3M0kasIVtVfPil6CzvhyWq3wwi760hucU0LL8wfjpln4xi8xw2/f6SOUQEx1HU1sczE3HbJCP8BsyxMSvfbT2MpbDlR+hvltT6l1anq5RrdwJnTRr7XP3swY/4G/bfU6EtUoqC5jD9OFfJ2GAq23/eHYdWvATPSmlmXqGoZCzb9qH6mWyMiufk56+19DBDxCEzRPe66jXFKFT3a6Byxfw0uD0yy9mA7Rw/INr+3cIlgMh5v9Mpvcs=
    JWT_SECRET: AgCBPo2NIb3I5IfZojAMjRql890NAHBPhBDBN++GTyeCCdB4zCODujZFOsL91t72wgwnDHsRpjhZo1H3/fI8oC9qdI/GuIT+2Why+66wOtmV6vlYkK/RG7ZMLZTb1l41GTdNGg/b+1bPRcUftboO6QqK1NANzMjyO7Ex8Y2KpgyjptW4xEIZgLBB/0CDtzfkzjAnP1WbpNSIGl0XjhBlclBnH8ETrO0sg/LJbMl4kI1uDIHV2+FhT/jnOFAmtDRscED7J1s6kMKkAUbuUJLx7AApW/sqqFSiiRv9edxGUMY/9osHYexQ0XCtJzgADYRrSp2au2f/CFs7oIEQNdeV6mVq2Gg5vtfw81l4FmY8SNh6Nn3eRBLu4x4CQI587B3+BfUNwpt5tk3nS68Od9ylerJ4xMwhmeynt6xDYVF3vhZZXXs0NpllXEtJE4MU5mMTexedyS0IplvMcyTaxZftu7RyVHHhhtsz12XoojbTB94QxE2kTLT0i5yNYyl0unz6nYCiWT7+hlcGRhkCcs0sVs8jqhI0pvW29lFkZpEGrezKEWWL8oWq1i//gxzn38QYWJt740du9eKmrMuVxW0TPJ7YL/UCVQ6lnC2pVKXo/2GVhBA1QWrUFfoh/YNUQpnrQNigTBDCmWMWGqUzmHbA/lnYZOxhHbnmduJkj0BuyaKZeKB3H4+Ctfz+zN7ZKljT3fl7lHxuCjHkJIaE1rbwKkXp9sEgfh7SeA6O/KUH3DNNuTKtzxdiIHgXalywAMNQV47dBpoaU53bSp4oUfnqn4JE
  template:
    metadata:
      creationTimestamp: null
      name: billing-secret
      namespace: billing-prod
