---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: billing-secret
  namespace: billing-prod
spec:
  encryptedData:
    DB_PASSWORD: AgBiuyaMFB08wo7kv0Qex5dnIzYQBs4lDx25Q0wqIcSZCprzlTHBTINFdjuuCMYM+yrLJ/EG+TmSu+lIBKBKoY48FWq+xOacq1e8zC6zx0IhmSsFVRELhIa7VthITlVPaZLRJtkZtApKqRVb7jbxKKv3/VbLMkG/QydJeqtXRkSUfFIrMR9d6RfXHjCC1+1fLhS8Lc5dbUhYzoTvlgrfLggEXf1Jluk2e6t66deN2yvN5A3YbiTa00K5cUXW4T581jnoDDmb5nSDoau/O58ym92oiGeRpowECmNJMRJEgIhOCNAW3f2RNiOyNenEsJ3LG+JRYzzvzP0fvJ+3VdKdQycFK9S1WpqntllYYB6gHBT2Dh0lrf0pmHoB1Ts9nXqXwwNA/jSA30kRCF4eaqYLWbC0BX3nr/+7Ag8nTriiyVYha8Vmu749Lk832WS3i5h1uy4RaWKk6rByoH4iWnRdyYz4AFCkk8rZKNYGS1zX93GppFhOWwGdUkc40hKhg5fGQixK88Ia5p/i+bOq0Evo54HkICthFRG+CJ/9Ld4KXF4Z9i1ZED7wl2u9F1UxNxnLlHs/pL7hvI+O1rcCPiaidNR469kaHVjnlE3PurbZhvTKEshiyQzmzLavFSFQhUY7OUmmAjpwg+SDtSkdfDePwJ8SOzPTAZtNmXl3A8fpxJwohAELWe4BwlB+WeBxDRoDXzcBNON0VtfavQPQ/0aur44=
    JWT_SECRET: AgC2F0lbK4H/k6VkdKYCGAP9Sal+XbpXFgGcAnuEsqNRbmGaav1zTb+e00aOiUkjF14aBdAHurX4VR/sbW9G0/gOg5TjaZHx/rKQLHeH1B0q6y4u2nFmgF/1KwupHmRfPThBY9N3Yuvwc4ftry6bA7myheEYvgx904Jrhu+ZrST3DOoNE3a4/Ph6og8XWtCnN3+tYf+agY/T0u0RLNfgbj1TDe8ZUbKyucV0Hh4HVFMa/Dtzpl2gCRcAR+ZqEugw2Ej0RllXhB53hdu4PZdgYOXJxY8WLyVmZOFShyeQzGydOSiR7bgpYuseYDnlEru1151aEcH7zbJRJQaN+s0UbS5AklggTLlnPx9NQFod/MSBAwRPpnwCf4cCUI2DmdIv2j+RAHRhuaw0lPin3gLQXIOJ7LOetryr6ZIVzszpPEoKvqqD2mLkhm7PtAl8+5J4Wfh5Zcn2bigq2F/AV4GFutSwGCgNXBswQrx3mPife3tvFJB5atRQ/VfVZc/p3UbRNMq7oRTiQ5IkTYYJbO7j3ZJxxyXI2jK/XNHS1p/IuhnsYiEl+sne/b3ANeac8+01n4ZWr7CNY1WoYBMTS2dVqg+0MJJGtmjFDhVKiRGikUAfoZ3PNi3RQzJIyOSxeREvNe1PBwWnZob5tIX8xyUuY/K9wObMWStS/gV48DNn1b5Y74U7jaRb4VbaYP+TQYFcMMKH59Q1ikro3lGBmnrULc5t9+3Z6fewKgyIaRk7luAEkz8K2l7g09BD7RKw6/LzmUqtS2iJwsAc82BK8AP9iVR3
  template:
    metadata:
      creationTimestamp: null
      name: billing-secret
      namespace: billing-prod
