name: usage-service
port: 8084
image:
  repository: 005988778995.dkr.ecr.us-east-1.amazonaws.com/billing/usage-service
  tag: "13"
dbConfigMapKey: USAGE_DATASOURCE_URL
extraEnv:
  - name: KAFKA_BOOTSTRAP_SERVERS
    valueFrom: KAFKA_BOOTSTRAP_SERVERS
  - name: CUSTOMER_SERVICE_URL
    valueFrom: CUSTOMER_SERVICE_URL
  - name: CATALOG_SERVICE_URL
    valueFrom: CATALOG_SERVICE_URL
  - name: SUBSCRIPTION_SERVICE_URL
    valueFrom: SUBSCRIPTION_SERVICE_URL
