name: customer-service
port: 8081
image:
  repository: 005988778995.dkr.ecr.us-east-1.amazonaws.com/billing/customer-service
  tag: "latest"
dbConfigMapKey: CUSTOMER_DATASOURCE_URL
extraEnv:
  - name: KAFKA_BOOTSTRAP_SERVERS
    valueFrom: KAFKA_BOOTSTRAP_SERVERS
