name: subscription-service
port: 8083
image:
  repository: 005988778995.dkr.ecr.us-east-1.amazonaws.com/billing/subscription-service
  tag: "latest"
extraEnv: []
dbConfigMapKey: SUBSCRIPTION_DATASOURCE_URL
