name: authentication-service
port: 8087
image:
  repository: 005988778995.dkr.ecr.us-east-1.amazonaws.com/billing/authentication-service
  tag: "13"
dbConfigMapKey: AUTH_DATASOURCE_URL
extraEnv:
  - name: BOUTIQUE_SERVICE_URL
    valueFrom: BOUTIQUE_SERVICE_URL
extraSecretEnv:
  - name: JWT_SECRET
    key: JWT_SECRET
